# Generated by Django 5.1.7 on 2025-04-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='full_text',
            field=models.TextField(blank=True),
        ),
    ]
