# Generated by Django 5.1.7 on 2025-04-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_olympiad_date_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='answers',
            new_name='answer',
        ),
    ]
