# Generated by Django 5.1.7 on 2025-04-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_olympiad_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
